### ISSUE TITLE
pass httpx timeout as parameter

### ISSUE THREAD

**Issue by thomas-rotszyld** [jeremyschulman/aio-ipfabric#31]
Hello Jeremy, 

Could be nice to have the possibility to pass the httpx timeout as parameter:

https://github.com/jeremyschulman/aio-ipfabric/blob/main/aioipfabric/base_client.py#L188

https://github.com/jeremyschulman/aio-ipfabric/blob/3306949f8b90438f8a1d28ed0976d8be4c8a90cc/aioipfabric/api.py#L82

**Comment by jeremyschulman** [comment]
@thomas-rotszyld - agreed.  I have this update staged in my dev environment now.  I plan to release the new version with this support today or tomorrow.

**Comment by jeremyschulman** [comment]
Added support in v0.9.0
https://pypi.org/project/aio-ipfabric/0.9.0/
